apiVersion: argoproj.io/v1alpha1
kind: Application
metadata: 
  name: dev-project
  namespace: argocd
spec: 
  destination: 
    namespace: ns-1
    server: "https://kubernetes.default.svc"
  project: dev-project
  source: 
    path: guestbook
    repoURL: "https://github.com/Ishii-Taiki/argocd-demo.git"
    targetRevision: main
  syncPolicy:
    syncOptions:
      - CreateNamespace=true